// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// EdFiPersonReference
    /// </summary>
    [DataContract(Name = "edFi_personReference")]
    public partial class EdFiPersonReference : IEquatable<EdFiPersonReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiPersonReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiPersonReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiPersonReference" /> class.
        /// </summary>
        /// <param name="personId">A unique alphanumeric code assigned to a person. (required).</param>
        /// <param name="sourceSystemDescriptor">This descriptor defines the originating record source system for the person. (required).</param>
        /// <param name="link">link.</param>
        public EdFiPersonReference(string personId = default, string sourceSystemDescriptor = default, Link link = default)
        {
            PersonId = personId ?? throw new ArgumentNullException("personId is a required property for EdFiPersonReference and cannot be null");
            SourceSystemDescriptor = sourceSystemDescriptor ?? throw new ArgumentNullException("sourceSystemDescriptor is a required property for EdFiPersonReference and cannot be null");
            Link = link;
        }

        /// <summary>
        /// A unique alphanumeric code assigned to a person.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a person.</value>
        [DataMember(Name = "personId", IsRequired = true, EmitDefaultValue = false)]
        public string PersonId { get; set; }

        /// <summary>
        /// This descriptor defines the originating record source system for the person.
        /// </summary>
        /// <value>This descriptor defines the originating record source system for the person.</value>
        [DataMember(Name = "sourceSystemDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string SourceSystemDescriptor { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public Link Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class EdFiPersonReference {\n");
            _ = sb.Append("  PersonId: ").Append(PersonId).Append("\n");
            _ = sb.Append("  SourceSystemDescriptor: ").Append(SourceSystemDescriptor).Append("\n");
            _ = sb.Append("  Link: ").Append(Link).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as EdFiPersonReference);
        }

        /// <summary>
        /// Returns true if EdFiPersonReference instances are equal
        /// </summary>
        /// <param name="input">Instance of EdFiPersonReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdFiPersonReference input)
        {
            return input != null
&& (
                    PersonId == input.PersonId ||
                    (PersonId != null &&
                    PersonId.Equals(input.PersonId))
                ) &&
                (
                    SourceSystemDescriptor == input.SourceSystemDescriptor ||
                    (SourceSystemDescriptor != null &&
                    SourceSystemDescriptor.Equals(input.SourceSystemDescriptor))
                ) &&
                (
                    Link == input.Link ||
                    (Link != null &&
                    Link.Equals(input.Link))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (PersonId != null)
                {
                    hashCode = (hashCode * 59) + PersonId.GetHashCode();
                }
                if (SourceSystemDescriptor != null)
                {
                    hashCode = (hashCode * 59) + SourceSystemDescriptor.GetHashCode();
                }
                if (Link != null)
                {
                    hashCode = (hashCode * 59) + Link.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // PersonId (string) maxLength
            if (PersonId != null && PersonId.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PersonId, length must be less than 32.", new[] { "PersonId" });
            }

            // SourceSystemDescriptor (string) maxLength
            if (SourceSystemDescriptor != null && SourceSystemDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SourceSystemDescriptor, length must be less than 306.", new[] { "SourceSystemDescriptor" });
            }

            yield break;
        }
    }

}
