// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// EdFiStudentAcademicRecordReference
    /// </summary>
    [DataContract(Name = "edFi_studentAcademicRecordReference")]
    public partial class EdFiStudentAcademicRecordReference : IEquatable<EdFiStudentAcademicRecordReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAcademicRecordReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected EdFiStudentAcademicRecordReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="EdFiStudentAcademicRecordReference" /> class.
        /// </summary>
        /// <param name="educationOrganizationId">The identifier assigned to an education organization. (required).</param>
        /// <param name="schoolYear">The identifier for the school year. (required).</param>
        /// <param name="studentUniqueId">A unique alphanumeric code assigned to a student. (required).</param>
        /// <param name="termDescriptor">The term for the session during the school year. (required).</param>
        /// <param name="link">link.</param>
        public EdFiStudentAcademicRecordReference(int educationOrganizationId = default, int schoolYear = default, string studentUniqueId = default, string termDescriptor = default, Link link = default)
        {
            EducationOrganizationId = educationOrganizationId;
            SchoolYear = schoolYear;
            StudentUniqueId = studentUniqueId ?? throw new ArgumentNullException("studentUniqueId is a required property for EdFiStudentAcademicRecordReference and cannot be null");
            TermDescriptor = termDescriptor ?? throw new ArgumentNullException("termDescriptor is a required property for EdFiStudentAcademicRecordReference and cannot be null");
            Link = link;
        }

        /// <summary>
        /// The identifier assigned to an education organization.
        /// </summary>
        /// <value>The identifier assigned to an education organization.</value>
        [DataMember(Name = "educationOrganizationId", IsRequired = true, EmitDefaultValue = false)]
        public int EducationOrganizationId { get; set; }

        /// <summary>
        /// The identifier for the school year.
        /// </summary>
        /// <value>The identifier for the school year.</value>
        [DataMember(Name = "schoolYear", IsRequired = true, EmitDefaultValue = false)]
        public int SchoolYear { get; set; }

        /// <summary>
        /// A unique alphanumeric code assigned to a student.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a student.</value>
        [DataMember(Name = "studentUniqueId", IsRequired = true, EmitDefaultValue = false)]
        public string StudentUniqueId { get; set; }

        /// <summary>
        /// The term for the session during the school year.
        /// </summary>
        /// <value>The term for the session during the school year.</value>
        [DataMember(Name = "termDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string TermDescriptor { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public Link Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class EdFiStudentAcademicRecordReference {\n");
            _ = sb.Append("  EducationOrganizationId: ").Append(EducationOrganizationId).Append("\n");
            _ = sb.Append("  SchoolYear: ").Append(SchoolYear).Append("\n");
            _ = sb.Append("  StudentUniqueId: ").Append(StudentUniqueId).Append("\n");
            _ = sb.Append("  TermDescriptor: ").Append(TermDescriptor).Append("\n");
            _ = sb.Append("  Link: ").Append(Link).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as EdFiStudentAcademicRecordReference);
        }

        /// <summary>
        /// Returns true if EdFiStudentAcademicRecordReference instances are equal
        /// </summary>
        /// <param name="input">Instance of EdFiStudentAcademicRecordReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(EdFiStudentAcademicRecordReference input)
        {
            return input != null
&& (
                    EducationOrganizationId == input.EducationOrganizationId ||
                    EducationOrganizationId.Equals(input.EducationOrganizationId)
                ) &&
                (
                    SchoolYear == input.SchoolYear ||
                    SchoolYear.Equals(input.SchoolYear)
                ) &&
                (
                    StudentUniqueId == input.StudentUniqueId ||
                    (StudentUniqueId != null &&
                    StudentUniqueId.Equals(input.StudentUniqueId))
                ) &&
                (
                    TermDescriptor == input.TermDescriptor ||
                    (TermDescriptor != null &&
                    TermDescriptor.Equals(input.TermDescriptor))
                ) &&
                (
                    Link == input.Link ||
                    (Link != null &&
                    Link.Equals(input.Link))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = (hashCode * 59) + EducationOrganizationId.GetHashCode();
                hashCode = (hashCode * 59) + SchoolYear.GetHashCode();
                if (StudentUniqueId != null)
                {
                    hashCode = (hashCode * 59) + StudentUniqueId.GetHashCode();
                }
                if (TermDescriptor != null)
                {
                    hashCode = (hashCode * 59) + TermDescriptor.GetHashCode();
                }
                if (Link != null)
                {
                    hashCode = (hashCode * 59) + Link.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // StudentUniqueId (string) maxLength
            if (StudentUniqueId != null && StudentUniqueId.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for StudentUniqueId, length must be less than 32.", new[] { "StudentUniqueId" });
            }

            // TermDescriptor (string) maxLength
            if (TermDescriptor != null && TermDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TermDescriptor, length must be less than 306.", new[] { "TermDescriptor" });
            }

            yield break;
        }
    }

}
