// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmRubricDimension
    /// </summary>
    [DataContract(Name = "tpdm_rubricDimension")]
    public partial class TpdmRubricDimension : IEquatable<TpdmRubricDimension>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmRubricDimension" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmRubricDimension() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmRubricDimension" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="rubricRating">The rating achieved for the rubric dimension. (required).</param>
        /// <param name="evaluationElementReference">evaluationElementReference (required).</param>
        /// <param name="criterionDescription">The criterion description for the rubric dimension. (required).</param>
        /// <param name="dimensionOrder">The order for the rubric dimension..</param>
        /// <param name="rubricRatingLevelDescriptor">The rating level achieved for the rubric dimension..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        public TpdmRubricDimension(string id = default, int rubricRating = default, TpdmEvaluationElementReference evaluationElementReference = default, string criterionDescription = default, int? dimensionOrder = default, string rubricRatingLevelDescriptor = default, string etag = default)
        {
            RubricRating = rubricRating;
            EvaluationElementReference = evaluationElementReference ?? throw new ArgumentNullException("evaluationElementReference is a required property for TpdmRubricDimension and cannot be null");
            CriterionDescription = criterionDescription ?? throw new ArgumentNullException("criterionDescription is a required property for TpdmRubricDimension and cannot be null");
            Id = id;
            DimensionOrder = dimensionOrder;
            RubricRatingLevelDescriptor = rubricRatingLevelDescriptor;
            Etag = etag;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The rating achieved for the rubric dimension.
        /// </summary>
        /// <value>The rating achieved for the rubric dimension.</value>
        [DataMember(Name = "rubricRating", IsRequired = true, EmitDefaultValue = false)]
        public int RubricRating { get; set; }

        /// <summary>
        /// Gets or Sets EvaluationElementReference
        /// </summary>
        [DataMember(Name = "evaluationElementReference", IsRequired = true, EmitDefaultValue = false)]
        public TpdmEvaluationElementReference EvaluationElementReference { get; set; }

        /// <summary>
        /// The criterion description for the rubric dimension.
        /// </summary>
        /// <value>The criterion description for the rubric dimension.</value>
        [DataMember(Name = "criterionDescription", IsRequired = true, EmitDefaultValue = false)]
        public string CriterionDescription { get; set; }

        /// <summary>
        /// The order for the rubric dimension.
        /// </summary>
        /// <value>The order for the rubric dimension.</value>
        [DataMember(Name = "dimensionOrder", EmitDefaultValue = true)]
        public int? DimensionOrder { get; set; }

        /// <summary>
        /// The rating level achieved for the rubric dimension.
        /// </summary>
        /// <value>The rating level achieved for the rubric dimension.</value>
        [DataMember(Name = "rubricRatingLevelDescriptor", EmitDefaultValue = true)]
        public string RubricRatingLevelDescriptor { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmRubricDimension {\n");
            _ = sb.Append("  Id: ").Append(Id).Append("\n");
            _ = sb.Append("  RubricRating: ").Append(RubricRating).Append("\n");
            _ = sb.Append("  EvaluationElementReference: ").Append(EvaluationElementReference).Append("\n");
            _ = sb.Append("  CriterionDescription: ").Append(CriterionDescription).Append("\n");
            _ = sb.Append("  DimensionOrder: ").Append(DimensionOrder).Append("\n");
            _ = sb.Append("  RubricRatingLevelDescriptor: ").Append(RubricRatingLevelDescriptor).Append("\n");
            _ = sb.Append("  Etag: ").Append(Etag).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmRubricDimension);
        }

        /// <summary>
        /// Returns true if TpdmRubricDimension instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmRubricDimension to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmRubricDimension input)
        {
            return input != null
&& (
                    Id == input.Id ||
                    (Id != null &&
                    Id.Equals(input.Id))
                ) &&
                (
                    RubricRating == input.RubricRating ||
                    RubricRating.Equals(input.RubricRating)
                ) &&
                (
                    EvaluationElementReference == input.EvaluationElementReference ||
                    (EvaluationElementReference != null &&
                    EvaluationElementReference.Equals(input.EvaluationElementReference))
                ) &&
                (
                    CriterionDescription == input.CriterionDescription ||
                    (CriterionDescription != null &&
                    CriterionDescription.Equals(input.CriterionDescription))
                ) &&
                (
                    DimensionOrder == input.DimensionOrder ||
                    (DimensionOrder != null &&
                    DimensionOrder.Equals(input.DimensionOrder))
                ) &&
                (
                    RubricRatingLevelDescriptor == input.RubricRatingLevelDescriptor ||
                    (RubricRatingLevelDescriptor != null &&
                    RubricRatingLevelDescriptor.Equals(input.RubricRatingLevelDescriptor))
                ) &&
                (
                    Etag == input.Etag ||
                    (Etag != null &&
                    Etag.Equals(input.Etag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Id != null)
                {
                    hashCode = (hashCode * 59) + Id.GetHashCode();
                }
                hashCode = (hashCode * 59) + RubricRating.GetHashCode();
                if (EvaluationElementReference != null)
                {
                    hashCode = (hashCode * 59) + EvaluationElementReference.GetHashCode();
                }
                if (CriterionDescription != null)
                {
                    hashCode = (hashCode * 59) + CriterionDescription.GetHashCode();
                }
                if (DimensionOrder != null)
                {
                    hashCode = (hashCode * 59) + DimensionOrder.GetHashCode();
                }
                if (RubricRatingLevelDescriptor != null)
                {
                    hashCode = (hashCode * 59) + RubricRatingLevelDescriptor.GetHashCode();
                }
                if (Etag != null)
                {
                    hashCode = (hashCode * 59) + Etag.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // CriterionDescription (string) maxLength
            if (CriterionDescription != null && CriterionDescription.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CriterionDescription, length must be less than 1024.", new[] { "CriterionDescription" });
            }

            // RubricRatingLevelDescriptor (string) maxLength
            if (RubricRatingLevelDescriptor != null && RubricRatingLevelDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for RubricRatingLevelDescriptor, length must be less than 306.", new[] { "RubricRatingLevelDescriptor" });
            }

            yield break;
        }
    }

}
