// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmSurveyResponsePersonTargetAssociation
    /// </summary>
    [DataContract(Name = "tpdm_surveyResponsePersonTargetAssociation")]
    public partial class TpdmSurveyResponsePersonTargetAssociation : IEquatable<TpdmSurveyResponsePersonTargetAssociation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmSurveyResponsePersonTargetAssociation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmSurveyResponsePersonTargetAssociation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmSurveyResponsePersonTargetAssociation" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="personReference">personReference (required).</param>
        /// <param name="surveyResponseReference">surveyResponseReference (required).</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        public TpdmSurveyResponsePersonTargetAssociation(string id = default, EdFiPersonReference personReference = default, EdFiSurveyResponseReference surveyResponseReference = default, string etag = default)
        {
            PersonReference = personReference ?? throw new ArgumentNullException("personReference is a required property for TpdmSurveyResponsePersonTargetAssociation and cannot be null");
            SurveyResponseReference = surveyResponseReference ?? throw new ArgumentNullException("surveyResponseReference is a required property for TpdmSurveyResponsePersonTargetAssociation and cannot be null");
            Id = id;
            Etag = etag;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets PersonReference
        /// </summary>
        [DataMember(Name = "personReference", IsRequired = true, EmitDefaultValue = false)]
        public EdFiPersonReference PersonReference { get; set; }

        /// <summary>
        /// Gets or Sets SurveyResponseReference
        /// </summary>
        [DataMember(Name = "surveyResponseReference", IsRequired = true, EmitDefaultValue = false)]
        public EdFiSurveyResponseReference SurveyResponseReference { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmSurveyResponsePersonTargetAssociation {\n");
            _ = sb.Append("  Id: ").Append(Id).Append("\n");
            _ = sb.Append("  PersonReference: ").Append(PersonReference).Append("\n");
            _ = sb.Append("  SurveyResponseReference: ").Append(SurveyResponseReference).Append("\n");
            _ = sb.Append("  Etag: ").Append(Etag).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmSurveyResponsePersonTargetAssociation);
        }

        /// <summary>
        /// Returns true if TpdmSurveyResponsePersonTargetAssociation instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmSurveyResponsePersonTargetAssociation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmSurveyResponsePersonTargetAssociation input)
        {
            return input != null
&& (
                    Id == input.Id ||
                    (Id != null &&
                    Id.Equals(input.Id))
                ) &&
                (
                    PersonReference == input.PersonReference ||
                    (PersonReference != null &&
                    PersonReference.Equals(input.PersonReference))
                ) &&
                (
                    SurveyResponseReference == input.SurveyResponseReference ||
                    (SurveyResponseReference != null &&
                    SurveyResponseReference.Equals(input.SurveyResponseReference))
                ) &&
                (
                    Etag == input.Etag ||
                    (Etag != null &&
                    Etag.Equals(input.Etag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Id != null)
                {
                    hashCode = (hashCode * 59) + Id.GetHashCode();
                }
                if (PersonReference != null)
                {
                    hashCode = (hashCode * 59) + PersonReference.GetHashCode();
                }
                if (SurveyResponseReference != null)
                {
                    hashCode = (hashCode * 59) + SurveyResponseReference.GetHashCode();
                }
                if (Etag != null)
                {
                    hashCode = (hashCode * 59) + Etag.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
