// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmCandidateTelephone
    /// </summary>
    [DataContract(Name = "tpdm_candidateTelephone")]
    public partial class TpdmCandidateTelephone : IEquatable<TpdmCandidateTelephone>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateTelephone" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmCandidateTelephone() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateTelephone" /> class.
        /// </summary>
        /// <param name="telephoneNumberTypeDescriptor">The type of communication number listed for an individual or organization. (required).</param>
        /// <param name="telephoneNumber">The telephone number including the area code, and extension, if applicable. (required).</param>
        /// <param name="doNotPublishIndicator">An indication that the telephone number should not be published..</param>
        /// <param name="orderOfPriority">The order of priority assigned to telephone numbers to define which number to attempt first, second, etc..</param>
        /// <param name="textMessageCapabilityIndicator">An indication that the telephone number is technically capable of sending and receiving Short Message Service (SMS) text messages..</param>
        public TpdmCandidateTelephone(string telephoneNumberTypeDescriptor = default, string telephoneNumber = default, bool? doNotPublishIndicator = default, int? orderOfPriority = default, bool? textMessageCapabilityIndicator = default)
        {
            TelephoneNumberTypeDescriptor = telephoneNumberTypeDescriptor ?? throw new ArgumentNullException("telephoneNumberTypeDescriptor is a required property for TpdmCandidateTelephone and cannot be null");
            TelephoneNumber = telephoneNumber ?? throw new ArgumentNullException("telephoneNumber is a required property for TpdmCandidateTelephone and cannot be null");
            DoNotPublishIndicator = doNotPublishIndicator;
            OrderOfPriority = orderOfPriority;
            TextMessageCapabilityIndicator = textMessageCapabilityIndicator;
        }

        /// <summary>
        /// The type of communication number listed for an individual or organization.
        /// </summary>
        /// <value>The type of communication number listed for an individual or organization.</value>
        [DataMember(Name = "telephoneNumberTypeDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string TelephoneNumberTypeDescriptor { get; set; }

        /// <summary>
        /// The telephone number including the area code, and extension, if applicable.
        /// </summary>
        /// <value>The telephone number including the area code, and extension, if applicable.</value>
        [DataMember(Name = "telephoneNumber", IsRequired = true, EmitDefaultValue = false)]
        public string TelephoneNumber { get; set; }

        /// <summary>
        /// An indication that the telephone number should not be published.
        /// </summary>
        /// <value>An indication that the telephone number should not be published.</value>
        [DataMember(Name = "doNotPublishIndicator", EmitDefaultValue = true)]
        public bool? DoNotPublishIndicator { get; set; }

        /// <summary>
        /// The order of priority assigned to telephone numbers to define which number to attempt first, second, etc.
        /// </summary>
        /// <value>The order of priority assigned to telephone numbers to define which number to attempt first, second, etc.</value>
        [DataMember(Name = "orderOfPriority", EmitDefaultValue = true)]
        public int? OrderOfPriority { get; set; }

        /// <summary>
        /// An indication that the telephone number is technically capable of sending and receiving Short Message Service (SMS) text messages.
        /// </summary>
        /// <value>An indication that the telephone number is technically capable of sending and receiving Short Message Service (SMS) text messages.</value>
        [DataMember(Name = "textMessageCapabilityIndicator", EmitDefaultValue = true)]
        public bool? TextMessageCapabilityIndicator { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmCandidateTelephone {\n");
            _ = sb.Append("  TelephoneNumberTypeDescriptor: ").Append(TelephoneNumberTypeDescriptor).Append("\n");
            _ = sb.Append("  TelephoneNumber: ").Append(TelephoneNumber).Append("\n");
            _ = sb.Append("  DoNotPublishIndicator: ").Append(DoNotPublishIndicator).Append("\n");
            _ = sb.Append("  OrderOfPriority: ").Append(OrderOfPriority).Append("\n");
            _ = sb.Append("  TextMessageCapabilityIndicator: ").Append(TextMessageCapabilityIndicator).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmCandidateTelephone);
        }

        /// <summary>
        /// Returns true if TpdmCandidateTelephone instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmCandidateTelephone to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmCandidateTelephone input)
        {
            return input != null
&& (
                    TelephoneNumberTypeDescriptor == input.TelephoneNumberTypeDescriptor ||
                    (TelephoneNumberTypeDescriptor != null &&
                    TelephoneNumberTypeDescriptor.Equals(input.TelephoneNumberTypeDescriptor))
                ) &&
                (
                    TelephoneNumber == input.TelephoneNumber ||
                    (TelephoneNumber != null &&
                    TelephoneNumber.Equals(input.TelephoneNumber))
                ) &&
                (
                    DoNotPublishIndicator == input.DoNotPublishIndicator ||
                    (DoNotPublishIndicator != null &&
                    DoNotPublishIndicator.Equals(input.DoNotPublishIndicator))
                ) &&
                (
                    OrderOfPriority == input.OrderOfPriority ||
                    (OrderOfPriority != null &&
                    OrderOfPriority.Equals(input.OrderOfPriority))
                ) &&
                (
                    TextMessageCapabilityIndicator == input.TextMessageCapabilityIndicator ||
                    (TextMessageCapabilityIndicator != null &&
                    TextMessageCapabilityIndicator.Equals(input.TextMessageCapabilityIndicator))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (TelephoneNumberTypeDescriptor != null)
                {
                    hashCode = (hashCode * 59) + TelephoneNumberTypeDescriptor.GetHashCode();
                }
                if (TelephoneNumber != null)
                {
                    hashCode = (hashCode * 59) + TelephoneNumber.GetHashCode();
                }
                if (DoNotPublishIndicator != null)
                {
                    hashCode = (hashCode * 59) + DoNotPublishIndicator.GetHashCode();
                }
                if (OrderOfPriority != null)
                {
                    hashCode = (hashCode * 59) + OrderOfPriority.GetHashCode();
                }
                if (TextMessageCapabilityIndicator != null)
                {
                    hashCode = (hashCode * 59) + TextMessageCapabilityIndicator.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // TelephoneNumberTypeDescriptor (string) maxLength
            if (TelephoneNumberTypeDescriptor != null && TelephoneNumberTypeDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TelephoneNumberTypeDescriptor, length must be less than 306.", new[] { "TelephoneNumberTypeDescriptor" });
            }

            // TelephoneNumber (string) maxLength
            if (TelephoneNumber != null && TelephoneNumber.Length > 24)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TelephoneNumber, length must be less than 24.", new[] { "TelephoneNumber" });
            }

            yield break;
        }
    }

}
