// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmEvaluation
    /// </summary>
    [DataContract(Name = "tpdm_evaluation")]
    public partial class TpdmEvaluation : IEquatable<TpdmEvaluation>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluation" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmEvaluation() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluation" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="evaluationTitle">The name or title of the evaluation. (required).</param>
        /// <param name="performanceEvaluationReference">performanceEvaluationReference (required).</param>
        /// <param name="evaluationDescription">The long description of the Evaluation..</param>
        /// <param name="evaluationTypeDescriptor">The type of the evaluation (e.g., observation, principal, peer, student survey, student growth)..</param>
        /// <param name="interRaterReliabilityScore">A score indicating how much homogeneity, or consensus, there is in the ratings given by judges. Most commonly a percentage scale (1-100).</param>
        /// <param name="maxRating">The maximum summary numerical rating or score for the evaluation..</param>
        /// <param name="minRating">The minimum summary numerical rating or score for the evaluation. If omitted, assumed to be 0.0..</param>
        /// <param name="ratingLevels">An unordered collection of evaluationRatingLevels. The descriptive level(s) of ratings (cut scores) for the evaluation..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        public TpdmEvaluation(string id = default, string evaluationTitle = default, TpdmPerformanceEvaluationReference performanceEvaluationReference = default, string evaluationDescription = default, string evaluationTypeDescriptor = default, int? interRaterReliabilityScore = default, double? maxRating = default, double? minRating = default, List<TpdmEvaluationRatingLevel> ratingLevels = default, string etag = default)
        {
            EvaluationTitle = evaluationTitle ?? throw new ArgumentNullException("evaluationTitle is a required property for TpdmEvaluation and cannot be null");
            PerformanceEvaluationReference = performanceEvaluationReference ?? throw new ArgumentNullException("performanceEvaluationReference is a required property for TpdmEvaluation and cannot be null");
            Id = id;
            EvaluationDescription = evaluationDescription;
            EvaluationTypeDescriptor = evaluationTypeDescriptor;
            InterRaterReliabilityScore = interRaterReliabilityScore;
            MaxRating = maxRating;
            MinRating = minRating;
            RatingLevels = ratingLevels;
            Etag = etag;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// The name or title of the evaluation.
        /// </summary>
        /// <value>The name or title of the evaluation.</value>
        [DataMember(Name = "evaluationTitle", IsRequired = true, EmitDefaultValue = false)]
        public string EvaluationTitle { get; set; }

        /// <summary>
        /// Gets or Sets PerformanceEvaluationReference
        /// </summary>
        [DataMember(Name = "performanceEvaluationReference", IsRequired = true, EmitDefaultValue = false)]
        public TpdmPerformanceEvaluationReference PerformanceEvaluationReference { get; set; }

        /// <summary>
        /// The long description of the Evaluation.
        /// </summary>
        /// <value>The long description of the Evaluation.</value>
        [DataMember(Name = "evaluationDescription", EmitDefaultValue = true)]
        public string EvaluationDescription { get; set; }

        /// <summary>
        /// The type of the evaluation (e.g., observation, principal, peer, student survey, student growth).
        /// </summary>
        /// <value>The type of the evaluation (e.g., observation, principal, peer, student survey, student growth).</value>
        [DataMember(Name = "evaluationTypeDescriptor", EmitDefaultValue = true)]
        public string EvaluationTypeDescriptor { get; set; }

        /// <summary>
        /// A score indicating how much homogeneity, or consensus, there is in the ratings given by judges. Most commonly a percentage scale (1-100)
        /// </summary>
        /// <value>A score indicating how much homogeneity, or consensus, there is in the ratings given by judges. Most commonly a percentage scale (1-100)</value>
        [DataMember(Name = "interRaterReliabilityScore", EmitDefaultValue = true)]
        public int? InterRaterReliabilityScore { get; set; }

        /// <summary>
        /// The maximum summary numerical rating or score for the evaluation.
        /// </summary>
        /// <value>The maximum summary numerical rating or score for the evaluation.</value>
        [DataMember(Name = "maxRating", EmitDefaultValue = true)]
        public double? MaxRating { get; set; }

        /// <summary>
        /// The minimum summary numerical rating or score for the evaluation. If omitted, assumed to be 0.0.
        /// </summary>
        /// <value>The minimum summary numerical rating or score for the evaluation. If omitted, assumed to be 0.0.</value>
        [DataMember(Name = "minRating", EmitDefaultValue = true)]
        public double? MinRating { get; set; }

        /// <summary>
        /// An unordered collection of evaluationRatingLevels. The descriptive level(s) of ratings (cut scores) for the evaluation.
        /// </summary>
        /// <value>An unordered collection of evaluationRatingLevels. The descriptive level(s) of ratings (cut scores) for the evaluation.</value>
        [DataMember(Name = "ratingLevels", EmitDefaultValue = false)]
        public List<TpdmEvaluationRatingLevel> RatingLevels { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmEvaluation {\n");
            _ = sb.Append("  Id: ").Append(Id).Append("\n");
            _ = sb.Append("  EvaluationTitle: ").Append(EvaluationTitle).Append("\n");
            _ = sb.Append("  PerformanceEvaluationReference: ").Append(PerformanceEvaluationReference).Append("\n");
            _ = sb.Append("  EvaluationDescription: ").Append(EvaluationDescription).Append("\n");
            _ = sb.Append("  EvaluationTypeDescriptor: ").Append(EvaluationTypeDescriptor).Append("\n");
            _ = sb.Append("  InterRaterReliabilityScore: ").Append(InterRaterReliabilityScore).Append("\n");
            _ = sb.Append("  MaxRating: ").Append(MaxRating).Append("\n");
            _ = sb.Append("  MinRating: ").Append(MinRating).Append("\n");
            _ = sb.Append("  RatingLevels: ").Append(RatingLevels).Append("\n");
            _ = sb.Append("  Etag: ").Append(Etag).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmEvaluation);
        }

        /// <summary>
        /// Returns true if TpdmEvaluation instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmEvaluation to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmEvaluation input)
        {
            return input != null
&& (
                    Id == input.Id ||
                    (Id != null &&
                    Id.Equals(input.Id))
                ) &&
                (
                    EvaluationTitle == input.EvaluationTitle ||
                    (EvaluationTitle != null &&
                    EvaluationTitle.Equals(input.EvaluationTitle))
                ) &&
                (
                    PerformanceEvaluationReference == input.PerformanceEvaluationReference ||
                    (PerformanceEvaluationReference != null &&
                    PerformanceEvaluationReference.Equals(input.PerformanceEvaluationReference))
                ) &&
                (
                    EvaluationDescription == input.EvaluationDescription ||
                    (EvaluationDescription != null &&
                    EvaluationDescription.Equals(input.EvaluationDescription))
                ) &&
                (
                    EvaluationTypeDescriptor == input.EvaluationTypeDescriptor ||
                    (EvaluationTypeDescriptor != null &&
                    EvaluationTypeDescriptor.Equals(input.EvaluationTypeDescriptor))
                ) &&
                (
                    InterRaterReliabilityScore == input.InterRaterReliabilityScore ||
                    (InterRaterReliabilityScore != null &&
                    InterRaterReliabilityScore.Equals(input.InterRaterReliabilityScore))
                ) &&
                (
                    MaxRating == input.MaxRating ||
                    (MaxRating != null &&
                    MaxRating.Equals(input.MaxRating))
                ) &&
                (
                    MinRating == input.MinRating ||
                    (MinRating != null &&
                    MinRating.Equals(input.MinRating))
                ) &&
                (
                    RatingLevels == input.RatingLevels ||
                    RatingLevels != null &&
                    input.RatingLevels != null &&
                    RatingLevels.SequenceEqual(input.RatingLevels)
                ) &&
                (
                    Etag == input.Etag ||
                    (Etag != null &&
                    Etag.Equals(input.Etag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Id != null)
                {
                    hashCode = (hashCode * 59) + Id.GetHashCode();
                }
                if (EvaluationTitle != null)
                {
                    hashCode = (hashCode * 59) + EvaluationTitle.GetHashCode();
                }
                if (PerformanceEvaluationReference != null)
                {
                    hashCode = (hashCode * 59) + PerformanceEvaluationReference.GetHashCode();
                }
                if (EvaluationDescription != null)
                {
                    hashCode = (hashCode * 59) + EvaluationDescription.GetHashCode();
                }
                if (EvaluationTypeDescriptor != null)
                {
                    hashCode = (hashCode * 59) + EvaluationTypeDescriptor.GetHashCode();
                }
                if (InterRaterReliabilityScore != null)
                {
                    hashCode = (hashCode * 59) + InterRaterReliabilityScore.GetHashCode();
                }
                if (MaxRating != null)
                {
                    hashCode = (hashCode * 59) + MaxRating.GetHashCode();
                }
                if (MinRating != null)
                {
                    hashCode = (hashCode * 59) + MinRating.GetHashCode();
                }
                if (RatingLevels != null)
                {
                    hashCode = (hashCode * 59) + RatingLevels.GetHashCode();
                }
                if (Etag != null)
                {
                    hashCode = (hashCode * 59) + Etag.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // EvaluationTitle (string) maxLength
            if (EvaluationTitle != null && EvaluationTitle.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationTitle, length must be less than 50.", new[] { "EvaluationTitle" });
            }

            // EvaluationDescription (string) maxLength
            if (EvaluationDescription != null && EvaluationDescription.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationDescription, length must be less than 255.", new[] { "EvaluationDescription" });
            }

            // EvaluationTypeDescriptor (string) maxLength
            if (EvaluationTypeDescriptor != null && EvaluationTypeDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationTypeDescriptor, length must be less than 306.", new[] { "EvaluationTypeDescriptor" });
            }

            yield break;
        }
    }

}
