// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;
using OpenAPIDateConverter = EdFi.OdsApi.Sdk.Client.OpenAPIDateConverter;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization
    /// </summary>
    [DataContract(Name = "tpdm_candidateEducatorPreparationProgramAssociationDegreeSpecialization")]
    public partial class TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization : IEquatable<TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization" /> class.
        /// </summary>
        /// <param name="majorSpecialization">The major area for a degree or area of specialization for a certificate. (required).</param>
        /// <param name="endDate">The month, day, and year on which the Teacher Candidate exited the declared specialization..</param>
        /// <param name="minorSpecialization">The minor area for a degree or area of specialization for a certificate..</param>
        public TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization(string majorSpecialization = default, DateTime? endDate = default, string minorSpecialization = default)
        {
            MajorSpecialization = majorSpecialization ?? throw new ArgumentNullException("majorSpecialization is a required property for TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization and cannot be null");
            EndDate = endDate;
            MinorSpecialization = minorSpecialization;
        }

        /// <summary>
        /// The major area for a degree or area of specialization for a certificate.
        /// </summary>
        /// <value>The major area for a degree or area of specialization for a certificate.</value>
        [DataMember(Name = "majorSpecialization", IsRequired = true, EmitDefaultValue = false)]
        public string MajorSpecialization { get; set; }

        /// <summary>
        /// The month, day, and year on which the Teacher Candidate exited the declared specialization.
        /// </summary>
        /// <value>The month, day, and year on which the Teacher Candidate exited the declared specialization.</value>
        [DataMember(Name = "endDate", EmitDefaultValue = true)]
        [JsonConverter(typeof(OpenAPIDateConverter))]
        public DateTime? EndDate { get; set; }

        /// <summary>
        /// The minor area for a degree or area of specialization for a certificate.
        /// </summary>
        /// <value>The minor area for a degree or area of specialization for a certificate.</value>
        [DataMember(Name = "minorSpecialization", EmitDefaultValue = true)]
        public string MinorSpecialization { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization {\n");
            _ = sb.Append("  MajorSpecialization: ").Append(MajorSpecialization).Append("\n");
            _ = sb.Append("  EndDate: ").Append(EndDate).Append("\n");
            _ = sb.Append("  MinorSpecialization: ").Append(MinorSpecialization).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization);
        }

        /// <summary>
        /// Returns true if TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmCandidateEducatorPreparationProgramAssociationDegreeSpecialization input)
        {
            return input != null
&& (
                    MajorSpecialization == input.MajorSpecialization ||
                    (MajorSpecialization != null &&
                    MajorSpecialization.Equals(input.MajorSpecialization))
                ) &&
                (
                    EndDate == input.EndDate ||
                    (EndDate != null &&
                    EndDate.Equals(input.EndDate))
                ) &&
                (
                    MinorSpecialization == input.MinorSpecialization ||
                    (MinorSpecialization != null &&
                    MinorSpecialization.Equals(input.MinorSpecialization))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (MajorSpecialization != null)
                {
                    hashCode = (hashCode * 59) + MajorSpecialization.GetHashCode();
                }
                if (EndDate != null)
                {
                    hashCode = (hashCode * 59) + EndDate.GetHashCode();
                }
                if (MinorSpecialization != null)
                {
                    hashCode = (hashCode * 59) + MinorSpecialization.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // MajorSpecialization (string) maxLength
            if (MajorSpecialization != null && MajorSpecialization.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MajorSpecialization, length must be less than 255.", new[] { "MajorSpecialization" });
            }

            // MinorSpecialization (string) maxLength
            if (MinorSpecialization != null && MinorSpecialization.Length > 255)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for MinorSpecialization, length must be less than 255.", new[] { "MinorSpecialization" });
            }

            yield break;
        }
    }

}
