// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmCredentialStudentAcademicRecord
    /// </summary>
    [DataContract(Name = "tpdm_credentialStudentAcademicRecord")]
    public partial class TpdmCredentialStudentAcademicRecord : IEquatable<TpdmCredentialStudentAcademicRecord>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCredentialStudentAcademicRecord" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmCredentialStudentAcademicRecord() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCredentialStudentAcademicRecord" /> class.
        /// </summary>
        /// <param name="studentAcademicRecordReference">studentAcademicRecordReference (required).</param>
        public TpdmCredentialStudentAcademicRecord(EdFiStudentAcademicRecordReference studentAcademicRecordReference = default)
        {
            StudentAcademicRecordReference = studentAcademicRecordReference ?? throw new ArgumentNullException("studentAcademicRecordReference is a required property for TpdmCredentialStudentAcademicRecord and cannot be null");
        }

        /// <summary>
        /// Gets or Sets StudentAcademicRecordReference
        /// </summary>
        [DataMember(Name = "studentAcademicRecordReference", IsRequired = true, EmitDefaultValue = false)]
        public EdFiStudentAcademicRecordReference StudentAcademicRecordReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmCredentialStudentAcademicRecord {\n");
            _ = sb.Append("  StudentAcademicRecordReference: ").Append(StudentAcademicRecordReference).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmCredentialStudentAcademicRecord);
        }

        /// <summary>
        /// Returns true if TpdmCredentialStudentAcademicRecord instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmCredentialStudentAcademicRecord to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmCredentialStudentAcademicRecord input)
        {
            return input != null
&& (StudentAcademicRecordReference == input.StudentAcademicRecordReference ||
                    (StudentAcademicRecordReference != null &&
                    StudentAcademicRecordReference.Equals(input.StudentAcademicRecordReference)));
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (StudentAcademicRecordReference != null)
                {
                    hashCode = (hashCode * 59) + StudentAcademicRecordReference.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
