// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmEvaluationRatingReference
    /// </summary>
    [DataContract(Name = "tpdm_evaluationRatingReference")]
    public partial class TpdmEvaluationRatingReference : IEquatable<TpdmEvaluationRatingReference>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluationRatingReference" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmEvaluationRatingReference() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluationRatingReference" /> class.
        /// </summary>
        /// <param name="educationOrganizationId">The identifier assigned to an education organization. (required).</param>
        /// <param name="evaluationDate">The date for the person&#39;s evaluation. (required).</param>
        /// <param name="evaluationPeriodDescriptor">The period for the evaluation. (required).</param>
        /// <param name="evaluationTitle">The name or title of the evaluation. (required).</param>
        /// <param name="performanceEvaluationTitle">An assigned unique identifier for the performance evaluation. (required).</param>
        /// <param name="performanceEvaluationTypeDescriptor">The type of performance evaluation conducted. (required).</param>
        /// <param name="personId">A unique alphanumeric code assigned to a person. (required).</param>
        /// <param name="schoolYear">The identifier for the school year. (required).</param>
        /// <param name="sourceSystemDescriptor">This descriptor defines the originating record source system for the person. (required).</param>
        /// <param name="termDescriptor">The term for the session during the school year. (required).</param>
        /// <param name="link">link.</param>
        public TpdmEvaluationRatingReference(int educationOrganizationId = default, DateTime evaluationDate = default, string evaluationPeriodDescriptor = default, string evaluationTitle = default, string performanceEvaluationTitle = default, string performanceEvaluationTypeDescriptor = default, string personId = default, int schoolYear = default, string sourceSystemDescriptor = default, string termDescriptor = default, Link link = default)
        {
            EducationOrganizationId = educationOrganizationId;
            EvaluationDate = evaluationDate;
            EvaluationPeriodDescriptor = evaluationPeriodDescriptor ?? throw new ArgumentNullException("evaluationPeriodDescriptor is a required property for TpdmEvaluationRatingReference and cannot be null");
            EvaluationTitle = evaluationTitle ?? throw new ArgumentNullException("evaluationTitle is a required property for TpdmEvaluationRatingReference and cannot be null");
            PerformanceEvaluationTitle = performanceEvaluationTitle ?? throw new ArgumentNullException("performanceEvaluationTitle is a required property for TpdmEvaluationRatingReference and cannot be null");
            PerformanceEvaluationTypeDescriptor = performanceEvaluationTypeDescriptor ?? throw new ArgumentNullException("performanceEvaluationTypeDescriptor is a required property for TpdmEvaluationRatingReference and cannot be null");
            PersonId = personId ?? throw new ArgumentNullException("personId is a required property for TpdmEvaluationRatingReference and cannot be null");
            SchoolYear = schoolYear;
            SourceSystemDescriptor = sourceSystemDescriptor ?? throw new ArgumentNullException("sourceSystemDescriptor is a required property for TpdmEvaluationRatingReference and cannot be null");
            TermDescriptor = termDescriptor ?? throw new ArgumentNullException("termDescriptor is a required property for TpdmEvaluationRatingReference and cannot be null");
            Link = link;
        }

        /// <summary>
        /// The identifier assigned to an education organization.
        /// </summary>
        /// <value>The identifier assigned to an education organization.</value>
        [DataMember(Name = "educationOrganizationId", IsRequired = true, EmitDefaultValue = false)]
        public int EducationOrganizationId { get; set; }

        /// <summary>
        /// The date for the person&#39;s evaluation.
        /// </summary>
        /// <value>The date for the person&#39;s evaluation.</value>
        [DataMember(Name = "evaluationDate", IsRequired = true, EmitDefaultValue = false)]
        public DateTime EvaluationDate { get; set; }

        /// <summary>
        /// The period for the evaluation.
        /// </summary>
        /// <value>The period for the evaluation.</value>
        [DataMember(Name = "evaluationPeriodDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string EvaluationPeriodDescriptor { get; set; }

        /// <summary>
        /// The name or title of the evaluation.
        /// </summary>
        /// <value>The name or title of the evaluation.</value>
        [DataMember(Name = "evaluationTitle", IsRequired = true, EmitDefaultValue = false)]
        public string EvaluationTitle { get; set; }

        /// <summary>
        /// An assigned unique identifier for the performance evaluation.
        /// </summary>
        /// <value>An assigned unique identifier for the performance evaluation.</value>
        [DataMember(Name = "performanceEvaluationTitle", IsRequired = true, EmitDefaultValue = false)]
        public string PerformanceEvaluationTitle { get; set; }

        /// <summary>
        /// The type of performance evaluation conducted.
        /// </summary>
        /// <value>The type of performance evaluation conducted.</value>
        [DataMember(Name = "performanceEvaluationTypeDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string PerformanceEvaluationTypeDescriptor { get; set; }

        /// <summary>
        /// A unique alphanumeric code assigned to a person.
        /// </summary>
        /// <value>A unique alphanumeric code assigned to a person.</value>
        [DataMember(Name = "personId", IsRequired = true, EmitDefaultValue = false)]
        public string PersonId { get; set; }

        /// <summary>
        /// The identifier for the school year.
        /// </summary>
        /// <value>The identifier for the school year.</value>
        [DataMember(Name = "schoolYear", IsRequired = true, EmitDefaultValue = false)]
        public int SchoolYear { get; set; }

        /// <summary>
        /// This descriptor defines the originating record source system for the person.
        /// </summary>
        /// <value>This descriptor defines the originating record source system for the person.</value>
        [DataMember(Name = "sourceSystemDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string SourceSystemDescriptor { get; set; }

        /// <summary>
        /// The term for the session during the school year.
        /// </summary>
        /// <value>The term for the session during the school year.</value>
        [DataMember(Name = "termDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string TermDescriptor { get; set; }

        /// <summary>
        /// Gets or Sets Link
        /// </summary>
        [DataMember(Name = "link", EmitDefaultValue = false)]
        public Link Link { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmEvaluationRatingReference {\n");
            _ = sb.Append("  EducationOrganizationId: ").Append(EducationOrganizationId).Append("\n");
            _ = sb.Append("  EvaluationDate: ").Append(EvaluationDate).Append("\n");
            _ = sb.Append("  EvaluationPeriodDescriptor: ").Append(EvaluationPeriodDescriptor).Append("\n");
            _ = sb.Append("  EvaluationTitle: ").Append(EvaluationTitle).Append("\n");
            _ = sb.Append("  PerformanceEvaluationTitle: ").Append(PerformanceEvaluationTitle).Append("\n");
            _ = sb.Append("  PerformanceEvaluationTypeDescriptor: ").Append(PerformanceEvaluationTypeDescriptor).Append("\n");
            _ = sb.Append("  PersonId: ").Append(PersonId).Append("\n");
            _ = sb.Append("  SchoolYear: ").Append(SchoolYear).Append("\n");
            _ = sb.Append("  SourceSystemDescriptor: ").Append(SourceSystemDescriptor).Append("\n");
            _ = sb.Append("  TermDescriptor: ").Append(TermDescriptor).Append("\n");
            _ = sb.Append("  Link: ").Append(Link).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmEvaluationRatingReference);
        }

        /// <summary>
        /// Returns true if TpdmEvaluationRatingReference instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmEvaluationRatingReference to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmEvaluationRatingReference input)
        {
            return input != null
&& (
                    EducationOrganizationId == input.EducationOrganizationId ||
                    EducationOrganizationId.Equals(input.EducationOrganizationId)
                ) &&
                (
                    EvaluationDate == input.EvaluationDate ||
                    EvaluationDate.Equals(input.EvaluationDate)
                ) &&
                (
                    EvaluationPeriodDescriptor == input.EvaluationPeriodDescriptor ||
                    (EvaluationPeriodDescriptor != null &&
                    EvaluationPeriodDescriptor.Equals(input.EvaluationPeriodDescriptor))
                ) &&
                (
                    EvaluationTitle == input.EvaluationTitle ||
                    (EvaluationTitle != null &&
                    EvaluationTitle.Equals(input.EvaluationTitle))
                ) &&
                (
                    PerformanceEvaluationTitle == input.PerformanceEvaluationTitle ||
                    (PerformanceEvaluationTitle != null &&
                    PerformanceEvaluationTitle.Equals(input.PerformanceEvaluationTitle))
                ) &&
                (
                    PerformanceEvaluationTypeDescriptor == input.PerformanceEvaluationTypeDescriptor ||
                    (PerformanceEvaluationTypeDescriptor != null &&
                    PerformanceEvaluationTypeDescriptor.Equals(input.PerformanceEvaluationTypeDescriptor))
                ) &&
                (
                    PersonId == input.PersonId ||
                    (PersonId != null &&
                    PersonId.Equals(input.PersonId))
                ) &&
                (
                    SchoolYear == input.SchoolYear ||
                    SchoolYear.Equals(input.SchoolYear)
                ) &&
                (
                    SourceSystemDescriptor == input.SourceSystemDescriptor ||
                    (SourceSystemDescriptor != null &&
                    SourceSystemDescriptor.Equals(input.SourceSystemDescriptor))
                ) &&
                (
                    TermDescriptor == input.TermDescriptor ||
                    (TermDescriptor != null &&
                    TermDescriptor.Equals(input.TermDescriptor))
                ) &&
                (
                    Link == input.Link ||
                    (Link != null &&
                    Link.Equals(input.Link))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                hashCode = (hashCode * 59) + EducationOrganizationId.GetHashCode();
                hashCode = (hashCode * 59) + EvaluationDate.GetHashCode();
                if (EvaluationPeriodDescriptor != null)
                {
                    hashCode = (hashCode * 59) + EvaluationPeriodDescriptor.GetHashCode();
                }
                if (EvaluationTitle != null)
                {
                    hashCode = (hashCode * 59) + EvaluationTitle.GetHashCode();
                }
                if (PerformanceEvaluationTitle != null)
                {
                    hashCode = (hashCode * 59) + PerformanceEvaluationTitle.GetHashCode();
                }
                if (PerformanceEvaluationTypeDescriptor != null)
                {
                    hashCode = (hashCode * 59) + PerformanceEvaluationTypeDescriptor.GetHashCode();
                }
                if (PersonId != null)
                {
                    hashCode = (hashCode * 59) + PersonId.GetHashCode();
                }
                hashCode = (hashCode * 59) + SchoolYear.GetHashCode();
                if (SourceSystemDescriptor != null)
                {
                    hashCode = (hashCode * 59) + SourceSystemDescriptor.GetHashCode();
                }
                if (TermDescriptor != null)
                {
                    hashCode = (hashCode * 59) + TermDescriptor.GetHashCode();
                }
                if (Link != null)
                {
                    hashCode = (hashCode * 59) + Link.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // EvaluationPeriodDescriptor (string) maxLength
            if (EvaluationPeriodDescriptor != null && EvaluationPeriodDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationPeriodDescriptor, length must be less than 306.", new[] { "EvaluationPeriodDescriptor" });
            }

            // EvaluationTitle (string) maxLength
            if (EvaluationTitle != null && EvaluationTitle.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationTitle, length must be less than 50.", new[] { "EvaluationTitle" });
            }

            // PerformanceEvaluationTitle (string) maxLength
            if (PerformanceEvaluationTitle != null && PerformanceEvaluationTitle.Length > 50)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PerformanceEvaluationTitle, length must be less than 50.", new[] { "PerformanceEvaluationTitle" });
            }

            // PerformanceEvaluationTypeDescriptor (string) maxLength
            if (PerformanceEvaluationTypeDescriptor != null && PerformanceEvaluationTypeDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PerformanceEvaluationTypeDescriptor, length must be less than 306.", new[] { "PerformanceEvaluationTypeDescriptor" });
            }

            // PersonId (string) maxLength
            if (PersonId != null && PersonId.Length > 32)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PersonId, length must be less than 32.", new[] { "PersonId" });
            }

            // SourceSystemDescriptor (string) maxLength
            if (SourceSystemDescriptor != null && SourceSystemDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for SourceSystemDescriptor, length must be less than 306.", new[] { "SourceSystemDescriptor" });
            }

            // TermDescriptor (string) maxLength
            if (TermDescriptor != null && TermDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TermDescriptor, length must be less than 306.", new[] { "TermDescriptor" });
            }

            yield break;
        }
    }

}
