// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmEvaluationElementRating
    /// </summary>
    [DataContract(Name = "tpdm_evaluationElementRating")]
    public partial class TpdmEvaluationElementRating : IEquatable<TpdmEvaluationElementRating>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluationElementRating" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmEvaluationElementRating() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmEvaluationElementRating" /> class.
        /// </summary>
        /// <param name="id">id.</param>
        /// <param name="evaluationElementReference">evaluationElementReference (required).</param>
        /// <param name="evaluationObjectiveRatingReference">evaluationObjectiveRatingReference (required).</param>
        /// <param name="areaOfRefinement">Area identified for person to refine or improve as part of the evaluation..</param>
        /// <param name="areaOfReinforcement">Area identified for reinforcement or positive feedback as part of the evaluation..</param>
        /// <param name="comments">Any comments about the performance evaluation to be captured..</param>
        /// <param name="evaluationElementRatingLevelDescriptor">The rating level achieved based upon the rating or score..</param>
        /// <param name="feedback">Feedback provided to the evaluated person..</param>
        /// <param name="results">An unordered collection of evaluationElementRatingResults. The numerical summary rating or score for the evaluation element..</param>
        /// <param name="etag">A unique system-generated value that identifies the version of the resource..</param>
        public TpdmEvaluationElementRating(string id = default, TpdmEvaluationElementReference evaluationElementReference = default, TpdmEvaluationObjectiveRatingReference evaluationObjectiveRatingReference = default, string areaOfRefinement = default, string areaOfReinforcement = default, string comments = default, string evaluationElementRatingLevelDescriptor = default, string feedback = default, List<TpdmEvaluationElementRatingResult> results = default, string etag = default)
        {
            EvaluationElementReference = evaluationElementReference ?? throw new ArgumentNullException("evaluationElementReference is a required property for TpdmEvaluationElementRating and cannot be null");
            EvaluationObjectiveRatingReference = evaluationObjectiveRatingReference ?? throw new ArgumentNullException("evaluationObjectiveRatingReference is a required property for TpdmEvaluationElementRating and cannot be null");
            Id = id;
            AreaOfRefinement = areaOfRefinement;
            AreaOfReinforcement = areaOfReinforcement;
            Comments = comments;
            EvaluationElementRatingLevelDescriptor = evaluationElementRatingLevelDescriptor;
            Feedback = feedback;
            Results = results;
            Etag = etag;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", EmitDefaultValue = false)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets EvaluationElementReference
        /// </summary>
        [DataMember(Name = "evaluationElementReference", IsRequired = true, EmitDefaultValue = false)]
        public TpdmEvaluationElementReference EvaluationElementReference { get; set; }

        /// <summary>
        /// Gets or Sets EvaluationObjectiveRatingReference
        /// </summary>
        [DataMember(Name = "evaluationObjectiveRatingReference", IsRequired = true, EmitDefaultValue = false)]
        public TpdmEvaluationObjectiveRatingReference EvaluationObjectiveRatingReference { get; set; }

        /// <summary>
        /// Area identified for person to refine or improve as part of the evaluation.
        /// </summary>
        /// <value>Area identified for person to refine or improve as part of the evaluation.</value>
        [DataMember(Name = "areaOfRefinement", EmitDefaultValue = true)]
        public string AreaOfRefinement { get; set; }

        /// <summary>
        /// Area identified for reinforcement or positive feedback as part of the evaluation.
        /// </summary>
        /// <value>Area identified for reinforcement or positive feedback as part of the evaluation.</value>
        [DataMember(Name = "areaOfReinforcement", EmitDefaultValue = true)]
        public string AreaOfReinforcement { get; set; }

        /// <summary>
        /// Any comments about the performance evaluation to be captured.
        /// </summary>
        /// <value>Any comments about the performance evaluation to be captured.</value>
        [DataMember(Name = "comments", EmitDefaultValue = true)]
        public string Comments { get; set; }

        /// <summary>
        /// The rating level achieved based upon the rating or score.
        /// </summary>
        /// <value>The rating level achieved based upon the rating or score.</value>
        [DataMember(Name = "evaluationElementRatingLevelDescriptor", EmitDefaultValue = true)]
        public string EvaluationElementRatingLevelDescriptor { get; set; }

        /// <summary>
        /// Feedback provided to the evaluated person.
        /// </summary>
        /// <value>Feedback provided to the evaluated person.</value>
        [DataMember(Name = "feedback", EmitDefaultValue = true)]
        public string Feedback { get; set; }

        /// <summary>
        /// An unordered collection of evaluationElementRatingResults. The numerical summary rating or score for the evaluation element.
        /// </summary>
        /// <value>An unordered collection of evaluationElementRatingResults. The numerical summary rating or score for the evaluation element.</value>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public List<TpdmEvaluationElementRatingResult> Results { get; set; }

        /// <summary>
        /// A unique system-generated value that identifies the version of the resource.
        /// </summary>
        /// <value>A unique system-generated value that identifies the version of the resource.</value>
        [DataMember(Name = "_etag", EmitDefaultValue = false)]
        public string Etag { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmEvaluationElementRating {\n");
            _ = sb.Append("  Id: ").Append(Id).Append("\n");
            _ = sb.Append("  EvaluationElementReference: ").Append(EvaluationElementReference).Append("\n");
            _ = sb.Append("  EvaluationObjectiveRatingReference: ").Append(EvaluationObjectiveRatingReference).Append("\n");
            _ = sb.Append("  AreaOfRefinement: ").Append(AreaOfRefinement).Append("\n");
            _ = sb.Append("  AreaOfReinforcement: ").Append(AreaOfReinforcement).Append("\n");
            _ = sb.Append("  Comments: ").Append(Comments).Append("\n");
            _ = sb.Append("  EvaluationElementRatingLevelDescriptor: ").Append(EvaluationElementRatingLevelDescriptor).Append("\n");
            _ = sb.Append("  Feedback: ").Append(Feedback).Append("\n");
            _ = sb.Append("  Results: ").Append(Results).Append("\n");
            _ = sb.Append("  Etag: ").Append(Etag).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmEvaluationElementRating);
        }

        /// <summary>
        /// Returns true if TpdmEvaluationElementRating instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmEvaluationElementRating to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmEvaluationElementRating input)
        {
            return input != null
&& (
                    Id == input.Id ||
                    (Id != null &&
                    Id.Equals(input.Id))
                ) &&
                (
                    EvaluationElementReference == input.EvaluationElementReference ||
                    (EvaluationElementReference != null &&
                    EvaluationElementReference.Equals(input.EvaluationElementReference))
                ) &&
                (
                    EvaluationObjectiveRatingReference == input.EvaluationObjectiveRatingReference ||
                    (EvaluationObjectiveRatingReference != null &&
                    EvaluationObjectiveRatingReference.Equals(input.EvaluationObjectiveRatingReference))
                ) &&
                (
                    AreaOfRefinement == input.AreaOfRefinement ||
                    (AreaOfRefinement != null &&
                    AreaOfRefinement.Equals(input.AreaOfRefinement))
                ) &&
                (
                    AreaOfReinforcement == input.AreaOfReinforcement ||
                    (AreaOfReinforcement != null &&
                    AreaOfReinforcement.Equals(input.AreaOfReinforcement))
                ) &&
                (
                    Comments == input.Comments ||
                    (Comments != null &&
                    Comments.Equals(input.Comments))
                ) &&
                (
                    EvaluationElementRatingLevelDescriptor == input.EvaluationElementRatingLevelDescriptor ||
                    (EvaluationElementRatingLevelDescriptor != null &&
                    EvaluationElementRatingLevelDescriptor.Equals(input.EvaluationElementRatingLevelDescriptor))
                ) &&
                (
                    Feedback == input.Feedback ||
                    (Feedback != null &&
                    Feedback.Equals(input.Feedback))
                ) &&
                (
                    Results == input.Results ||
                    Results != null &&
                    input.Results != null &&
                    Results.SequenceEqual(input.Results)
                ) &&
                (
                    Etag == input.Etag ||
                    (Etag != null &&
                    Etag.Equals(input.Etag))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (Id != null)
                {
                    hashCode = (hashCode * 59) + Id.GetHashCode();
                }
                if (EvaluationElementReference != null)
                {
                    hashCode = (hashCode * 59) + EvaluationElementReference.GetHashCode();
                }
                if (EvaluationObjectiveRatingReference != null)
                {
                    hashCode = (hashCode * 59) + EvaluationObjectiveRatingReference.GetHashCode();
                }
                if (AreaOfRefinement != null)
                {
                    hashCode = (hashCode * 59) + AreaOfRefinement.GetHashCode();
                }
                if (AreaOfReinforcement != null)
                {
                    hashCode = (hashCode * 59) + AreaOfReinforcement.GetHashCode();
                }
                if (Comments != null)
                {
                    hashCode = (hashCode * 59) + Comments.GetHashCode();
                }
                if (EvaluationElementRatingLevelDescriptor != null)
                {
                    hashCode = (hashCode * 59) + EvaluationElementRatingLevelDescriptor.GetHashCode();
                }
                if (Feedback != null)
                {
                    hashCode = (hashCode * 59) + Feedback.GetHashCode();
                }
                if (Results != null)
                {
                    hashCode = (hashCode * 59) + Results.GetHashCode();
                }
                if (Etag != null)
                {
                    hashCode = (hashCode * 59) + Etag.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // AreaOfRefinement (string) maxLength
            if (AreaOfRefinement != null && AreaOfRefinement.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AreaOfRefinement, length must be less than 1024.", new[] { "AreaOfRefinement" });
            }

            // AreaOfReinforcement (string) maxLength
            if (AreaOfReinforcement != null && AreaOfReinforcement.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AreaOfReinforcement, length must be less than 1024.", new[] { "AreaOfReinforcement" });
            }

            // Comments (string) maxLength
            if (Comments != null && Comments.Length > 1024)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Comments, length must be less than 1024.", new[] { "Comments" });
            }

            // EvaluationElementRatingLevelDescriptor (string) maxLength
            if (EvaluationElementRatingLevelDescriptor != null && EvaluationElementRatingLevelDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for EvaluationElementRatingLevelDescriptor, length must be less than 306.", new[] { "EvaluationElementRatingLevelDescriptor" });
            }

            // Feedback (string) maxLength
            if (Feedback != null && Feedback.Length > 2048)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Feedback, length must be less than 2048.", new[] { "Feedback" });
            }

            yield break;
        }
    }

}
