// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.
/*
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  *** 
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using System.Text;

namespace EdFi.OdsApi.Sdk.Models.All
{
    /// <summary>
    /// TpdmCandidateEducatorPreparationProgramAssociationCohortYear
    /// </summary>
    [DataContract(Name = "tpdm_candidateEducatorPreparationProgramAssociationCohortYear")]
    public partial class TpdmCandidateEducatorPreparationProgramAssociationCohortYear : IEquatable<TpdmCandidateEducatorPreparationProgramAssociationCohortYear>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateEducatorPreparationProgramAssociationCohortYear" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TpdmCandidateEducatorPreparationProgramAssociationCohortYear() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TpdmCandidateEducatorPreparationProgramAssociationCohortYear" /> class.
        /// </summary>
        /// <param name="cohortYearTypeDescriptor">The type of cohort year (9th grade, graduation). (required).</param>
        /// <param name="termDescriptor">The term associated with the cohort year; for example, the intended term of graduation..</param>
        /// <param name="schoolYearTypeReference">schoolYearTypeReference (required).</param>
        public TpdmCandidateEducatorPreparationProgramAssociationCohortYear(string cohortYearTypeDescriptor = default, string termDescriptor = default, EdFiSchoolYearTypeReference schoolYearTypeReference = default)
        {
            CohortYearTypeDescriptor = cohortYearTypeDescriptor ?? throw new ArgumentNullException("cohortYearTypeDescriptor is a required property for TpdmCandidateEducatorPreparationProgramAssociationCohortYear and cannot be null");
            SchoolYearTypeReference = schoolYearTypeReference ?? throw new ArgumentNullException("schoolYearTypeReference is a required property for TpdmCandidateEducatorPreparationProgramAssociationCohortYear and cannot be null");
            TermDescriptor = termDescriptor;
        }

        /// <summary>
        /// The type of cohort year (9th grade, graduation).
        /// </summary>
        /// <value>The type of cohort year (9th grade, graduation).</value>
        [DataMember(Name = "cohortYearTypeDescriptor", IsRequired = true, EmitDefaultValue = false)]
        public string CohortYearTypeDescriptor { get; set; }

        /// <summary>
        /// The term associated with the cohort year; for example, the intended term of graduation.
        /// </summary>
        /// <value>The term associated with the cohort year; for example, the intended term of graduation.</value>
        [DataMember(Name = "termDescriptor", EmitDefaultValue = true)]
        public string TermDescriptor { get; set; }

        /// <summary>
        /// Gets or Sets SchoolYearTypeReference
        /// </summary>
        [DataMember(Name = "schoolYearTypeReference", IsRequired = true, EmitDefaultValue = false)]
        public EdFiSchoolYearTypeReference SchoolYearTypeReference { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            _ = sb.Append("class TpdmCandidateEducatorPreparationProgramAssociationCohortYear {\n");
            _ = sb.Append("  CohortYearTypeDescriptor: ").Append(CohortYearTypeDescriptor).Append("\n");
            _ = sb.Append("  TermDescriptor: ").Append(TermDescriptor).Append("\n");
            _ = sb.Append("  SchoolYearTypeReference: ").Append(SchoolYearTypeReference).Append("\n");
            _ = sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return Equals(input as TpdmCandidateEducatorPreparationProgramAssociationCohortYear);
        }

        /// <summary>
        /// Returns true if TpdmCandidateEducatorPreparationProgramAssociationCohortYear instances are equal
        /// </summary>
        /// <param name="input">Instance of TpdmCandidateEducatorPreparationProgramAssociationCohortYear to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TpdmCandidateEducatorPreparationProgramAssociationCohortYear input)
        {
            return input != null
&& (
                    CohortYearTypeDescriptor == input.CohortYearTypeDescriptor ||
                    (CohortYearTypeDescriptor != null &&
                    CohortYearTypeDescriptor.Equals(input.CohortYearTypeDescriptor))
                ) &&
                (
                    TermDescriptor == input.TermDescriptor ||
                    (TermDescriptor != null &&
                    TermDescriptor.Equals(input.TermDescriptor))
                ) &&
                (
                    SchoolYearTypeReference == input.SchoolYearTypeReference ||
                    (SchoolYearTypeReference != null &&
                    SchoolYearTypeReference.Equals(input.SchoolYearTypeReference))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                if (CohortYearTypeDescriptor != null)
                {
                    hashCode = (hashCode * 59) + CohortYearTypeDescriptor.GetHashCode();
                }
                if (TermDescriptor != null)
                {
                    hashCode = (hashCode * 59) + TermDescriptor.GetHashCode();
                }
                if (SchoolYearTypeReference != null)
                {
                    hashCode = (hashCode * 59) + SchoolYearTypeReference.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            // CohortYearTypeDescriptor (string) maxLength
            if (CohortYearTypeDescriptor != null && CohortYearTypeDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for CohortYearTypeDescriptor, length must be less than 306.", new[] { "CohortYearTypeDescriptor" });
            }

            // TermDescriptor (string) maxLength
            if (TermDescriptor != null && TermDescriptor.Length > 306)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for TermDescriptor, length must be less than 306.", new[] { "TermDescriptor" });
            }

            yield break;
        }
    }

}
