// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eppeta.webapi.Evaluations.Models;

[Table("EvaluationElementRatingResult", Schema = "eppeta")]
public partial class EvaluationElementRatingResult
{
    public long EducationOrganizationId { get; set; }

    public DateTime EvaluationDate { get; set; }

    [Required]
    [StringLength(255)]
    public string EvaluationElementTitle { get; set; }

    [Required]
    [StringLength(50)]
    public string EvaluationObjectiveTitle { get; set; }

    public string EvaluationPeriodDescriptor { get; set; }

    [Required]
    [StringLength(50)]
    public string EvaluationTitle { get; set; }

    [Required]
    [StringLength(50)]
    public string PerformanceEvaluationTitle { get; set; }

    public string PerformanceEvaluationTypeDescriptor { get; set; }

    [Required]
    [StringLength(32)]
    public string PersonId { get; set; }

    public short SchoolYear { get; set; }

    public string SourceSystemDescriptor { get; set; }

    public string TermDescriptor { get; set; }

    [Column(TypeName = "decimal(6, 3)")]
    public decimal Rating { get; set; }

    [Required]
    [StringLength(50)]
    public string RatingResultTitle { get; set; }

    public string ResultDatatypeTypeDescriptor { get; set; }

    public DateTime CreateDate { get; set; }

    [Column("EdFi_Id")]
    [StringLength(50)]
    public string EdFiId { get; set; }

    [Required]
    [StringLength(225)]
    public string UserId { get; set; }

    [Key]
    public int Id { get; set; }
}
