// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using EdFi.OdsApi.Sdk.Models.All;
using Microsoft.EntityFrameworkCore;

namespace eppeta.webapi.Evaluations.Models;

[Table("EvaluationElement", Schema = "eppeta")]
public partial class EvaluationElement
{
    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public int Id { get; set; }

    [Required]
    public long EducationOrganizationId { get; set; }

    [Required]
    [StringLength(255)]
    public string EvaluationElementTitle { get; set; }

    [Required]
    [StringLength(50)]
    public string EvaluationObjectiveTitle { get; set; }

    [Required]
    [StringLength(306)]
    public string EvaluationPeriodDescriptor { get; set; }

    [Required]
    [StringLength(50)]
    public string EvaluationTitle { get; set; }

    [Required]
    [StringLength(50)]
    public string PerformanceEvaluationTitle { get; set; }

    [Required]
    [StringLength(306)]
    public string PerformanceEvaluationTypeDescriptor { get; set; }

    [Required]
    public short SchoolYear { get; set; }

    [Required]
    [StringLength(306)]
    public string TermDescriptor { get; set; }

    [StringLength(306)]
    public string EvaluationTypeDescriptor { get; set; }

    public DateTime CreateDate { get; set; }

    public DateTime LastModifiedDate { get; set; }

    [Required]
    [Column("EdFi_Id")]
    [StringLength(50)]
    public string EdFiId { get; set; }

    public static explicit operator EvaluationElement(TpdmEvaluationElement tpdmEvaluationElement)
    => new EvaluationElement
    {
        EvaluationElementTitle= tpdmEvaluationElement.EvaluationElementTitle,
        EvaluationTypeDescriptor = tpdmEvaluationElement.EvaluationTypeDescriptor,
        EdFiId = tpdmEvaluationElement.Id,
        EvaluationObjectiveTitle = tpdmEvaluationElement.EvaluationObjectiveReference.EvaluationObjectiveTitle,
        EducationOrganizationId = tpdmEvaluationElement.EvaluationObjectiveReference.EducationOrganizationId,
        EvaluationPeriodDescriptor = tpdmEvaluationElement.EvaluationObjectiveReference.EvaluationPeriodDescriptor,
        EvaluationTitle = tpdmEvaluationElement.EvaluationObjectiveReference.EvaluationTitle,
        PerformanceEvaluationTitle = tpdmEvaluationElement.EvaluationObjectiveReference.PerformanceEvaluationTitle,
        PerformanceEvaluationTypeDescriptor = tpdmEvaluationElement.EvaluationObjectiveReference.PerformanceEvaluationTypeDescriptor,
        SchoolYear = (short)tpdmEvaluationElement.EvaluationObjectiveReference.SchoolYear,
        TermDescriptor = tpdmEvaluationElement.EvaluationObjectiveReference.TermDescriptor
    };
    public static explicit operator TpdmEvaluationElement(EvaluationElement evaluationElement)
        => new TpdmEvaluationElement
        (
            evaluationObjectiveReference : new TpdmEvaluationObjectiveReference
            (
                educationOrganizationId : (int)evaluationElement.EducationOrganizationId,
                evaluationObjectiveTitle : evaluationElement.EvaluationObjectiveTitle,
                evaluationPeriodDescriptor : evaluationElement.EvaluationPeriodDescriptor,
                evaluationTitle : evaluationElement.EvaluationTitle,
                performanceEvaluationTitle : evaluationElement.PerformanceEvaluationTitle,
                performanceEvaluationTypeDescriptor : evaluationElement.PerformanceEvaluationTypeDescriptor,
                schoolYear : evaluationElement.SchoolYear,
                termDescriptor : evaluationElement.TermDescriptor
            ),
            evaluationElementTitle : evaluationElement.EvaluationElementTitle,
            evaluationTypeDescriptor : evaluationElement.EvaluationTypeDescriptor
        );
}
