// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace eppeta.webapi.Evaluations.Models;

[Table("PerformanceEvaluation", Schema = "eppeta")]
public partial class PerformanceEvaluation
{
    public int EducationOrganizationId { get; set; }

    public int EvaluationPeriodDescriptorId { get; set; }

    [Required]
    [StringLength(50)]
    public string PerformanceEvaluationTitle { get; set; }

    public int PerformanceEvaluationTypeDescriptorId { get; set; }

    public short SchoolYear { get; set; }

    public int TermDescriptorId { get; set; }

    [StringLength(255)]
    public string PerformanceEvaluationDescription { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime CreateDate { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime LastModifiedDate { get; set; }

    [Column("EdFi_Id")]
    [StringLength(50)]
    public string EdFiId { get; set; }

    [Key]
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]

    public int Id { get; set; }
}
