# SPDX-License-Identifier: Apache-2.0
# Licensed to the Ed-Fi Alliance under one or more agreements.
# The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
# See the LICENSE and NOTICES files in the project root for more information.

name: On Pull Request - React

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - "reactapp/**/*"
      - ".github/workflows/on-pullrequest-react.yml"
  workflow_dispatch:

jobs:
  run-react-tests:
    name: Run React tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/reactapp
        shell: bash
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Setup Node
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4.0.0
        with:
          node-version: "16"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Node modules cache
        id: modules-cache
        uses: actions/cache@704facf57e6136b1bc63b828d79edcd491f0ee84 #v3.3.2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.modules-cache.outputs.cache-hit != 'true' }}
        run: npm install

      # Eventually we'll add a linter here. See Meadowlark for eslint examples.

      - name: Build
        run: |
          # Temporarily set CI to false so that warnings are not treated as
          # errors. This is not what we want to do long term. When we're ready
          # to treat warnings as errors, simply remove this comment and the next line.
          CI=false
          npm run build

      - name: Initialize CodeQL
        uses: github/codeql-action/init@df32e399139a3050671466d7d9b3cbacc1cfd034 # codeql-bundle-v2.15.2
        with:
          languages: "javascript"
          setup-python-dependencies: false

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@df32e399139a3050671466d7d9b3cbacc1cfd034 # codeql-bundle-v2.15.2

